### ISSUE TITLE
Heroku - Web process failed to bind to $PORT within 90 seconds of launch

### ISSUE THREAD

**Issue by hminnnn** [pengrad/telegram-bot-heroku#1]
Hi! 
I'm facing an issue with this error: 

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
Stopping process with SIGKILL
Process exited with status 137
State changed from starting to crashed

Will this be solved if i were to set the port? Where do i set the port? I seen the Main.java where your port seems to be set here port(Integer.parseInt(portNumber)); but I'm not sure how to do that. If i were to fire a message to my bot after it says crashed, after a long while sometimes it starts running again on its own and then crashing again.  I'm doing a simple java app on maven.

Thanks!

**Comment by pengrad** [comment]
Hi!
In my template `port()` is a method of Spark framework to set where it should run.
If you use it as is then it should work for you too.

You say about maven, means you not actually using this template (here is Gradle + Spark).
You need to set port from heroku ENV to your app.
I'm sure SO can help for you
https://stackoverflow.com/questions/45557881/spring-boot-on-heroku-web-process-failed-to-bind-to-port-within-90-seconds-of?rq=1
https://stackoverflow.com/questions/36751071/heroku-web-process-failed-to-bind-to-port-within-90-seconds-of-launch-tootall

Good luck

**Comment by Baliba** [comment]
I have solved it go to this url :
https://github.com/Baliba/-Error-R10-Boot-timeout-

**Comment by bakwanyana** [comment]
We solved this by adding a Procfile to the root directory and adding the line below:
web: java $JAVA_OPTS -Dserver.port=$PORT -jar <path-to-jar> as per https://stackoverflow.com/questions/34066878/error-r10-boot-timeout-web-process-failed-to-bind-to-port-within-60-second

**Comment by SardorbekJavaDev** [comment]
I solved this by https://devcenter.heroku.com/articles/run-non-web-java-processes-on-heroku. 
this my simple Java  telegram bot  https://github.com/SardorbekJavaDev/CashbackBot
